### ISSUE TITLE
Does it make sense to expose `allReleaseNotesFor` Ionide.KeepAChangelog ?

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/KeepAChangelog#13]
Hello,

I am using Ionide.KeepAChangelog to parse a changelog in my release process and want to output the release notes inside the Github release text.

Right now, I copied the following code into my repository:

https://github.com/ionide/KeepAChangelog/blob/97b28d71060b5c19d3208e833ba6149d0781052b/src/Ionide.KeepAChangelog.Tasks/Library.fs#L20-L35

Because this is portion of the code doesn't have dependency on MSBuild, would it make sense to expose it from the Ionide.KeepAChangelog nuget? Like that people can access it easily if needed.

**Comment by baronfel** [comment]
I think that's a great idea 👍

**Comment by TheAngryByrd** [comment]
Definitely will help in miniscaffold!
