### ISSUE TITLE
Add a new line between the section header and the items?

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/KeepAChangelog#14]
Hello,

in the following code https://github.com/ionide/KeepAChangelog/blob/97b28d71060b5c19d3208e833ba6149d0781052b/src/Ionide.KeepAChangelog.Tasks/Library.fs#L20-L35

The items are put on the line directly after the section header and the items:

```md
### Added
* Line 1
* Line 2
```

however when a human write the changelog it is more common to have an empty line between the section header and the items:

```md
### Added

* Line 1
* Line 2
```

I looked at how you wrote the CHANGELOG.md and wrote it with an empty line.

The changes would just be:

```diff
- | items -> $"### {name}" :: items @ [ "" ]
+ | items -> $"### {name}" :: "" :: items @ [ "" ]
```

This is a cosmetic request in case someone look at the markdown directly without it being processed or copy paste it.

**Comment by baronfel** [comment]
This also makes good sense to do👍
