### ISSUE TITLE
The package misses some .NET 6 task dependencies.

### ISSUE THREAD

**Issue by teo-tsirpanis** [ionide/KeepAChangelog#18]
If you download the artifact at https://github.com/teo-tsirpanis/KeepAChangelog/actions/runs/2951365264, you will see this:

![image](https://user-images.githubusercontent.com/12659251/187295296-a59577a8-ea46-4cff-b660-6d61ef9fc262.png)

**Comment by baronfel** [comment]
Recent releases should have fixed this.
