### ISSUE TITLE
Could not load file or assembly FParsec in Visual Studio 2022

### ISSUE THREAD

**Issue by albertwoo** [ionide/KeepAChangelog#19]
**Describe the bug**
```text
ionide.keepachangelog.tasks\0.1.8\build\Ionide.KeepAChangelog.Tasks.targets(29,9): error MSB4018: The "Ionide.KeepAChangelog.Tasks.ParseChangeLogs" task failed unexpectedly.
ionide.keepachangelog.tasks\0.1.8\build\Ionide.KeepAChangelog.Tasks.targets(29,9): error MSB4018: System.IO.FileNotFoundException: Could not load file or assembly 'FParsec, Version=1.1.1.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
ionide.keepachangelog.tasks\0.1.8\build\Ionide.KeepAChangelog.Tasks.targets(29,9): error MSB4018: File name: 'FParsec, Version=1.1.1.0, Culture=neutral, PublicKeyToken=null'
ionide.keepachangelog.tasks\0.1.8\build\Ionide.KeepAChangelog.Tasks.targets(29,9): error MSB4018:    at KeepAChangelog.Tasks.ParseChangelogs.Execute()
ionide.keepachangelog.tasks\0.1.8\build\Ionide.KeepAChangelog.Tasks.targets(29,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
ionide.keepachangelog.tasks\0.1.8\build\Ionide.KeepAChangelog.Tasks.targets(29,9): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://github.com/slaveOftime/Fun.Build . (This is a very small repo, so it should be ok to use it to reproduce)
2. Open with Visual Studio 2022 and build the solution
3. Build will fail. But if use dotnet cli to build, it will success

**Expected behaviour**
Works for dotnet cli and Visual Studio.

**Environment (please complete the following information):**
 - OS: Windows11
 - Visual Studio 2022
 - dotnet SDK version: 6.0.400

**Comment by baronfel** [comment]
I believe this is going to be the same as #8 - right now the packages doesn't support VS (actually it doesn't support full-framework MSBuild) so we have to do some packaging work to make it compatible. It's just fallen by the wayside for me personally a bit in comparison to FSAC at the moment.

**Comment by baronfel** [comment]
Also maybe #18

**Comment by baronfel** [comment]
Recent releases (including @tboby's new PR) should mitigate this in the future.
