### ISSUE TITLE
Make the date of a release optional?

### ISSUE THREAD

**Issue by MangelMaxime** [ionide/KeepAChangelog#21]
Hello,

When converting a project which used `RELEASE_NOTES.md` instead of a `CHANGELOG.md` I believe it is common to not have the date of the release.

Right now, this means that I have to set fake date for each release for the parser to work. Would it be possible to relax the ` - <date>` portion of `### <version> - <date>`?

**Comment by baronfel** [comment]
I believe this is what the `Unreleased` set of changes would be for - you'd accumulate changes into this section and have some explicit action that converted the `Unreleased` section to a specific release with a given date.

**Comment by MangelMaxime** [comment]
This is indeed the use case of the `Unreleased` section. 

But when converting from an existing RELEASE_NOTES.md who has already several released without date I can't do that.

Current RELEASE_NOTES.md looks like that:

```md

### 4.1.4

* Fix #3438: Source maps
* Fix #3440: Don't curry arity-1 functions

### 4.1.3

* JS/TS/Rust: Added bigint log, log2, log10, minMag, maxMag
* TS: Fix extension of files in fable_modules with out dir

### 4.1.2

* Print minimum fable-library version from npm

### 4.1.1

* Fix fable-library package.json

...
```

**Comment by baronfel** [comment]
The KeepAChangelog spec requires _a_ date, but it makes no decision about the ordering of those dates - you could use unix epoch, jan 1 year 1, etc. and the tooling would behave. I would suggest making some kind of dummy/placeholder date in this case.

**Comment by MangelMaxime** [comment]
Ok, I will close.

Thank you
