### ISSUE TITLE
[Question] Can Ionide.KeepAChangelog be used alongside Paket?

### ISSUE THREAD

**Issue by mrboring** [ionide/KeepAChangelog#28]
I'm trying to use `Ionide.KeepAChangelog` alongside `Paket` and I'm receiving the following error:

`error NU1008: Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items: <list of package names>`

`NU1008` is a `Nuget` error. I'm not creating a  `Nuget` package in my application. My reason for using `Ionide.KeepAChangelog` is for auto-updating of version numbers.

I used [https://github.com/nojaf/telplin](https://github.com/nojaf/telplin) as a reference for using  `Ionide.KeepAChangelog`. I notice that this does not use `Paket`.

### Directory.Packages.props
```xml
<Project>
    <!-- Note: I've tried with the following commented and uncommented -->
    <!-- <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup> -->

    <ItemGroup>
        <PackageVersion Include="Ionide.KeepAChangelog.Tasks" Version="0.1.8" />
    </ItemGroup>
</Project>
```

### Directory.Build.props
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project>
    <PropertyGroup>
        <!-- Set up version and package release note generation from this changelog. -->
        <ChangelogFile>$(MSBuildThisFileDirectory)CHANGELOG.md</ChangelogFile>
        <!-- Common packaging properties for all packages in this repo -->
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <WarnOn>3390;$(WarnOn)</WarnOn>
        <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
        <Authors><REMOVED></Authors>
        <Product><REMOVED></Product>
        <Description><REMOVED></Description>
        <AssemblyTitle><REMOVED></AssemblyTitle>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Ionide.KeepAChangelog.Tasks" PrivateAssets="all"/>
    </ItemGroup>
</Project>
```

### CHANGELOG.md
```
# Changelog

## 2.0.0 - 2024-08-01

### Added

* Keep A Changelog
```

### Project.fsproj
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="<REMOVED>.Html.fs" />
    <Compile Include="<REMOVED>.Types.fs" />
    <Compile Include="<REMOVED>.Validation.fs" />
    <Compile Include="<REMOVED>.Helpers.fs" />
    <Compile Include="<REMOVED>.Email.fs" />
  </ItemGroup>
  <Import Project="..\..\.paket\Paket.Restore.targets" />
</Project>
```

**Comment by baronfel** [comment]
Yes, it can. we use it in [FsAutoComplete](https://github.com/ionide/FsAutoComplete/blob/main/paket.dependencies#L50).

The main problem you're doing is mixing NuGet CPM and Paket - you should never mix any usage of NuGet with Paket, they are not meant to be used in this way. Pick one or the other and use it exclusively.

How did you start down this mixed-mode path?

**Comment by mrboring** [comment]
I didn't think I was! Bear in mind that Directory.Packages.props, Directory.Build.props and CHANGELOG.md were added today in an attempt to use Ioninde.keepAChangelog. I did this based on viewing the sample repository I mentioned.

Is it the Directory.Packages.props that's causing the problem?

**Comment by baronfel** [comment]
If you're already using Paket, all you should have to do is:

* delete directory.package.props (this is a marker to nuget that you want to use CPM)
* remove the PackageReference to Ionide.KeepAchangelog.Tasks from your directory.build.props
* add the package via paket: `dotnet paket add Ionide.KeepAChangelog.Tasks` - this should add it to your paket.dependencies and paket.lock files

Then you should be good to go!

**Comment by mrboring** [comment]
Thanks. I followed the steps you suggested and everything is now working. I appreciate you taking the time to help.

**Comment by baronfel** [comment]
Glad to hear that you're all good to go! Happy hacking :)
