### ISSUE TITLE
New versions on Nuget

### ISSUE THREAD

**Issue by 64J0** [ionide/KeepAChangelog#34]
## Description:

Hey, hope you're good. I noticed that the [last version available on Nuget](https://www.nuget.org/packages/Ionide.KeepAChangelog.Tasks#versions-body-tab) for this package is 0.1.8 from 2022, even though the latest release is 0.2.0 from 2023. Why didn't this new release version got into Nuget? Are there plans to send it there?

**Comment by baronfel** [comment]
That release had a bug, but recently @tboby has fixed that. I'm waiting a bit to merge their flurry of cleanup PRs then we can release a fixed version.

**Comment by 64J0** [comment]
Got it, thanks for the explanation.
